services:
  database:
    image: postgres:17.5-alpine
    container_name: database
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env.template
    networks:
      - backend

  backend:
    restart: on-failure
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env.template
    networks:
      - backend

  frontend:
    restart: on-failure
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontend
      - backend

volumes:
  database:

networks:
  backend:
  frontend: